## Deliverable 2. Create a Customer Travel Destinations Map.

In [17]:
# Import dependencies.
import pandas as pd
import requests
import gmaps

# Import API key
from config import weather_api_key

#Gmaps Key
gmaps.configure(api_key=weather_api_key)

In [18]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Vacation_Search/WeatherPy_Database.csv")
city_data_df.head()

,Unnamed: 0,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Dikson,RU,73.5069,80.5464,35.69,84,30,7.07,scattered clouds
1,1,Atuona,PF,-9.8000,-139.0333,78.17,69,33,19.06,scattered clouds
2,2,Batemans Bay,AU,-35.7167,150.1833,52.11,60,86,7.83,light rain
3,3,Albany,US,42.6001,-73.9662,78.64,53,88,3.09,overcast clouds
4,4,Saint Anthony,US,45.0205,-93.2180,75.25,59,0,9.22,clear sky

In [19]:
# 2. Prompt the user to enter minimum and maximum temperature criteria  
max_temp = float(input("What would be your maximum heat that you would tolerate on your vacation? "))
min_temp = float(input("What would be your minimum heat that you would tolerate on your vacation? "))

What would be your maximum heat that you would tolerate on your vacation? 90
What would be your minimum heat that you would tolerate on your vacation? 70

In [20]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & 
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,Unnamed: 0,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,Atuona,PF,-9.8000,-139.0333,78.17,69,33,19.06,scattered clouds
3,3,Albany,US,42.6001,-73.9662,78.64,53,88,3.09,overcast clouds
4,4,Saint Anthony,US,45.0205,-93.2180,75.25,59,0,9.22,clear sky
6,6,Avarua,CK,-21.2078,-159.7750,82.45,69,20,14.97,few clouds
13,13,Bethel,US,41.3712,-73.4140,75.29,71,0,6.91,clear sky
16,16,Georgetown,MY,5.4112,100.3354,76.95,95,40,4.61,scattered clouds
20,20,Ahuimanu,US,21.4447,-157.8378,85.78,67,40,17.27,scattered clouds
23,23,Jamestown,US,42.0970,-79.2353,81.99,90,100,6.62,overcast clouds
28,28,Sao Felix Do Xingu,BR,-6.6447,-51.9950,75.90,69,70,2.95,broken clouds
33,33,Pacific Grove,US,36.6177,-121.9166,82.02,68,0,10.36,clear sky

In [21]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.isnull().sum()

Unnamed: 0             0
City                   0
Country                0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
dtype: int64

In [22]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()
clean_df

,Unnamed: 0,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,Atuona,PF,-9.8000,-139.0333,78.17,69,33,19.06,scattered clouds
3,3,Albany,US,42.6001,-73.9662,78.64,53,88,3.09,overcast clouds
4,4,Saint Anthony,US,45.0205,-93.2180,75.25,59,0,9.22,clear sky
6,6,Avarua,CK,-21.2078,-159.7750,82.45,69,20,14.97,few clouds
13,13,Bethel,US,41.3712,-73.4140,75.29,71,0,6.91,clear sky
...,...,...,...,...,...,...,...,...,...,...
714,714,Puerto Escondido,MX,15.8500,-97.0667,79.63,61,100,9.22,overcast clouds
715,715,Anton Lizardo,MX,19.0500,-95.9833,83.21,80,76,14.43,broken clouds
716,716,Fonte Boa,BR,-2.4959,-66.2662,72.37,97,22,0.11,few clouds
717,717,Gazojak,TM,41.1875,61.4036,79.65,23,6,9.31,clear sky
720,720,Aragarcas,BR,-15.8975,-52.2508,76.03,52,0,2.48,clear sky

In [23]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Atuona,PF,78.17,scattered clouds,-9.8000,-139.0333,
3,Albany,US,78.64,overcast clouds,42.6001,-73.9662,
4,Saint Anthony,US,75.25,clear sky,45.0205,-93.2180,
6,Avarua,CK,82.45,few clouds,-21.2078,-159.7750,
13,Bethel,US,75.29,clear sky,41.3712,-73.4140,
16,Georgetown,MY,76.95,scattered clouds,5.4112,100.3354,
20,Ahuimanu,US,85.78,scattered clouds,21.4447,-157.8378,
23,Jamestown,US,81.99,overcast clouds,42.0970,-79.2353,
28,Sao Felix Do Xingu,BR,75.90,broken clouds,-6.6447,-51.9950,
33,Pacific Grove,US,82.02,clear sky,36.6177,-121.9166,

In [24]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": weather_api_key
}


# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():

    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        
    except (IndexError):
        print("Hotel Not Found...skipping.")

Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.

Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.
Hotel Not Found...skipping.

In [16]:
# 7. Drop the rows where there is no Hotel Name.

clean_hotel_df = hotel_df.dropna(subset = ['Hotel Name'])
clean_hotel_df.reset_index(drop=True)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Batemans Bay,AU,52.11,light rain,-35.7167,150.1833,
1,Saint Anthony,US,75.25,clear sky,45.0205,-93.2180,
2,Dieppe,FR,55.98,broken clouds,49.7500,1.1667,
3,Narsaq,GL,53.82,clear sky,60.9167,-46.0500,
4,Bethel,US,75.29,clear sky,41.3712,-73.4140,
...,...,...,...,...,...,...,...
397,Fonte Boa,BR,72.37,few clouds,-2.4959,-66.2662,
398,Bressuire,FR,63.64,overcast clouds,46.9167,-0.5000,
399,Aragarcas,BR,76.03,clear sky,-15.8975,-52.2508,
400,Floro,NO,54.23,overcast clouds,61.5996,5.0328,
401,Kariba,ZW,62.65,clear sky,-16.5167,28.8000,

In [25]:
# 8a. Create the output File (CSV)
output_data_file = ""../Vacation_Search/WeatherPy_Database.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

SyntaxError: invalid syntax (3951606714.py, line 2)

In [26]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """

"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [12]:
# 11a. Add a marker layer for each city to the map. 

# 11b. Display the figure